# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection).
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);

PUT http://localhost:8088/api/event/1
Content-Type: application/json

{
    "repImageUrl" : "대표이미지 변경",
    "imageUrl" : "변경",
    "eventStart" : "2022-05-02",
    "eventEnd" : "2022-05-02",
    "expose" : false,
    "eventTitle" : "이벤트 제목",
    "eventSubTitle": "이벤트 부제목",
    "colorText" : "BLACK",
    "statusType" : "IN_PROGRESS"
}

###
